const CONSTANTS = {
    CHANGE_LOCATION: "CHANGE_LOCATION",
    MOVE_UNITS_START: "MOVE_UNITS_START",
    VIEWS: {
        LOCATIONS: "LOCATIONS",
        UNITS: "UNITS" 
    }
};

export default CONSTANTS;
