const CONSTANTS = {
    CHANGE_LOCATION: "CHANGE_LOCATION",
    MOVE_UNITS_START: "MOVE_UNITS_START",
    CANCEL_MOVE_UNITS: "CANCEL_MOVE_UNITS",
    MOVE_UNITS_CONFIRM: "MOVE_UNITS_CONFIRM",
    VIEWS: {
        LOCATIONS: "LOCATIONS",
        UNITS: "UNITS"
    }
};

export default CONSTANTS;
