const CONSTANTS = {
    CHANGE_LOCATION: "CHANGE_LOCATION",
    MOVE_UNITS_START: "MOVE_UNITS_START",
    CANCEL_MOVE_UNITS: "CANCEL_MOVE_UNITS",
    MOVE_UNITS_CONFIRM: "MOVE_UNITS_CONFIRM",
    NEXT_DAY: "NEXT_DAY",
    END_TICK: "END_TICK",
    SIMULATE_ATTACK: "SIMULATE_ATTACK",
    VIEWS: {
        LOCATIONS: "LOCATIONS",
        UNITS: "UNITS",
        SUMMARY: "SUMMARY"
    },
    TITLES: {
        LOCATIONS: 'Map Room',
        UNITS: "Deploy Units",
        SUMMARY: "Raven's Scrolls"
    }
};

export default CONSTANTS;
